services:
  - type: web
    name: eduspark-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn main:app"
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_KEY
